repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: check-merge-conflict

  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        pass_filenames: false
        args: ['--all', '--check']
      - id: clippy
        args: ['--all', '--all-features', '--', '-D', 'warnings']

  - repo: https://github.com/crate-ci/typos
    rev: v1.17.0
    hooks:
      - id: typos

  - repo: local
    hooks:
      - id: cargo-test
        name: cargo test
        description: Run cargo test
        entry: cargo test
        language: system
        types: [rust]
        pass_filenames: false
